name: Generate Resume PDF

on:
  push:
    branches: [master]
    # Avoid triggering on changes to data.yml to prevent loops
    paths-ignore:
      - '_data/data.yml'
      - 'assets/files/*'
  workflow_dispatch:

jobs:
  generate_resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Generate PDF from resume page
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://radugalbenu.github.io/print
          outputFile: ./assets/files/my_cv_${{ steps.vars.outputs.sha_short }}.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Update data.yml with new PDF link
        run: |
          pip install ruamel.yaml
          PDF_LINK="https://radugalbenu.github.io/assets/files/my_cv_${{ steps.vars.outputs.sha_short }}.pdf"
          python3 <<EOF
          from ruamel.yaml import YAML
          yaml = YAML()
          yaml.preserve_quotes = True
          path = "_data/data.yml"
          with open(path, "r") as f:
              data = yaml.load(f)
          data['sidebar']['pdf'] = PDF_LINK
          with open(path, "w") as f:
              yaml.dump(data, f)
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/data.yml assets/files/
          git commit -m "Update PDF resume and link in data.yml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}